# Generated by Django 5.1.6 on 2025-02-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_warehouse_order_product_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
