# Generated by Django 5.1.6 on 2025-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('to_produce', 'Do produkcji'), ('ready', 'Gotowy do wysyłki'), ('shipped', 'Wysłany')], default='to_produce', max_length=20),
        ),
    ]
