# Generated by Django 5.1.6 on 2025-03-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customuser_groups_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
