# Generated by Django 5.1.6 on 2025-03-17 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='object_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.demand'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='demand_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='demand_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demand',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demand',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
