# Generated by Django 5.1.6 on 2025-03-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_delivery_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='demand_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='demand',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='demand',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
