# Generated by Django 5.1.6 on 2025-03-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_address_stock_delete_item_delete_useraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.demand'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='api.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
