# Generated by Django 5.1.6 on 2025-03-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_delivery_demand_alter_delivery_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.address'),
        ),
    ]
